"""Sprint 12C — Task 2: merge `ai_assets` into `media_assets` (idempotent).

Why two collections existed:
  - `ai_assets` (Phase 2, Feb 2026) — stored TEXT copy assets generated by the
    legacy `/api/ai-ads/generate/{kind}` specialty pipeline. `payload` is a
    structured dict (e.g. `{platform, short, medium, long}` for social posts).
    Surface endpoints: `/api/ai-ads/assets[...]`
  - `media_assets` (Phase 8, Feb 2026) — stores IMAGE / VIDEO file assets with
    `storage_path`, `mime`, `kind="image|video"`. Surface: `/api/media/...`

Merge strategy:
  1. Copy every `ai_assets` document into `media_assets` (upsert by `id`), adding
     `source="ai_ads_legacy"` so:
       - `/api/ai-ads/assets*` can keep working (it now reads/writes
         `media_assets` filtered by `source="ai_ads_legacy"`).
       - `/api/media/assets*` keeps NOT showing them (Media Studio list endpoint
         already filters by source kind in (image|video); we keep that invariant
         by routing the legacy endpoint to source="ai_ads_legacy" only).
  2. Drop the `ai_assets` collection once the count matches.

This script is idempotent — re-running is a no-op.

Run:
    cd /app/backend && python3 -m migrations.merge_ai_assets [--dry-run] [--drop]
"""
from __future__ import annotations

import argparse
import os
import sys
from typing import Any, Dict

from pymongo import MongoClient


LEGACY_SOURCE = "ai_ads_legacy"


def main(dry_run: bool, drop: bool) -> int:
    mongo_url = os.environ.get("MONGO_URL")
    db_name = os.environ.get("DB_NAME")
    if not mongo_url or not db_name:
        print("ERROR: MONGO_URL or DB_NAME env not set", file=sys.stderr)
        return 2

    client = MongoClient(mongo_url)
    db = client[db_name]

    ai_count = db.ai_assets.count_documents({})
    media_legacy_count = db.media_assets.count_documents({"source": LEGACY_SOURCE})
    media_total_before = db.media_assets.count_documents({})

    print(f"[merge_ai_assets] ai_assets count        = {ai_count}")
    print(f"[merge_ai_assets] media_assets count     = {media_total_before}")
    print(f"[merge_ai_assets] media(source=legacy)   = {media_legacy_count}")

    if ai_count == 0 and not drop:
        print("[merge_ai_assets] ai_assets is empty — nothing to migrate.")
        return 0

    upserted = 0
    skipped = 0
    for src in db.ai_assets.find({}, {"_id": 0}):
        aid = src.get("id")
        if not aid:
            skipped += 1
            continue
        # Build merged doc. Preserve every existing media_assets field if a row
        # already exists (idempotent), only fill in the legacy-only fields.
        legacy_doc: Dict[str, Any] = {
            "id": aid,
            # Tag — make sure /api/ai-ads/assets queries can find these
            "source": LEGACY_SOURCE,
            # Media-asset shape compatibility (we don't carry a file)
            "filename": (src.get("title") or "Untitled")[:160],
            "kind": src.get("kind") or "text_asset",
            "mime": "application/json",
            "storage_path": None,
            "size_bytes": 0,
            "width": None,
            "height": None,
            "duration_seconds": None,
            "folder": None,
            "tags": src.get("tags") or [],
            "is_favorite": bool(src.get("is_favorite") or False),
            "status": src.get("status") or "active",
            # ai_assets-specific fields preserved verbatim:
            "title": src.get("title"),
            "platform": src.get("platform"),
            "industry": src.get("industry"),
            "campaign_id": src.get("campaign_id"),
            "payload": src.get("payload"),
            # Timestamps — keep both naming conventions so downstream filters work
            "created_at": src.get("created_at"),
            "uploaded_at": src.get("created_at"),
            "updated_at": src.get("updated_at") or src.get("created_at"),
        }
        if dry_run:
            print(f"  would upsert id={aid[:8]} kind={legacy_doc['kind']}")
            upserted += 1
            continue
        existing = db.media_assets.find_one({"id": aid}, {"_id": 1})
        if existing:
            # Don't clobber a media_assets row that happens to share an id
            db.media_assets.update_one(
                {"id": aid},
                {"$set": {k: v for k, v in legacy_doc.items() if v is not None or k in ("status", "payload")}},
            )
        else:
            db.media_assets.insert_one(legacy_doc)
        upserted += 1

    print(f"[merge_ai_assets] upserted = {upserted}, skipped (no id) = {skipped}")

    if drop and not dry_run:
        final_legacy = db.media_assets.count_documents({"source": LEGACY_SOURCE})
        if final_legacy < ai_count:
            print(
                f"[merge_ai_assets] REFUSING TO DROP: media_assets has {final_legacy} "
                f"legacy rows but ai_assets has {ai_count}. Investigate before dropping."
            )
            return 3
        try:
            db.ai_assets.drop()
            print("[merge_ai_assets] DROPPED ai_assets collection.")
        except Exception as e:  # noqa: BLE001
            print(f"[merge_ai_assets] drop failed: {e}")
            return 4

    print("[merge_ai_assets] done.")
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true", help="No writes; just report.")
    ap.add_argument("--drop", action="store_true", help="Drop ai_assets after upsert succeeds.")
    args = ap.parse_args()
    sys.exit(main(dry_run=args.dry_run, drop=args.drop))
